### PR TITLE
RFC: Modernize FFX

### PR DESCRIPTION
**Pull request by natekupp**
@jmmcd if you've got any spare cycles, would love a hand getting this across the finish line; I covered a lot of ground tonight but there's still a bit more to do.

Summary of this diff:

- Remove references to Python 2.5 / 2.6 - no one uses these anymore
- Modernizes Python code throughout (still more to do here)
- Update styles, e.g. all "s are 's, move camelCase to snake_case (although I missed a few)
- Add six for handling py2/3 compat
- Adds a Makefile, with `make validate` running pylint/black/isort and `make test` running tests
- Switches test implementation to pytest and makes iris data a test fixture
- moves pypi upload script to Makefile
- Updates CLI to use the Click Python library
- Make "approach" a namedtuple
- Break apart core.py into a module
- Make `Base` an `abc.ABCMeta`
- Drop custom file reading / sniffing in favor of just using `pandas.read_csv` - it's 2019, I think people having pandas is a safe assumption now :)
- Remove random license headers - this is what the `LICENSE` file is for

Still to-do:
- pylint / black / isort should run in Travis and fail the build if not in good shape
- full tests should run in Travis
- tox for python matrix (maybe?)
- still some implementation bugs introduced in the mass conversion
- remainder of camel case to snake case conversion
- use python logging library/levels instead of `if verbose:` everywhere 
- update README after this is all done
- this whole thing is sorely under-tested...

### CODE REVIEW

**Comment by natekupp** [comment]
I think probably the best place to start is to break this mega PR into smaller reviewable chunks that we can land safely, but if you feel comfortable just going for it, I’m happy to continue working with you in this branch until it’s ready to land

**Comment by jmmcd** [comment]
This sounds great! Unfortunately I won't have any time to spend on it before the new year :-/

I don't know anything about black, isort, Click, Travis, tox, coveralls -- so will be of no help on those. Will be happy to help with reviewing/writing tests/something else.

**Comment by natekupp** [comment]
No worries! I was actually able to squeeze in some time to get through most of merging it; I'm going to close this PR now since most of it has landed.

I'll also be away until the new year, but let's touch base in the new year on next steps. Happy holidays!

**Comment by jmmcd** [comment]
Sounds good! And the same to you.

**Pull request closed without merging**
