### PR TITLE
Making the sklearn estimator compliant

### PR DESCRIPTION
**Pull request by pizzooid**
Replaces #36

### CODE REVIEW

**Comment by pizzooid** [comment]
What should we do about this?
The job exceeded the maximum log length, and has been terminated.

**Comment by natekupp** [comment]
Hey @pizzooid thanks for adding this, and apologies for the delayed response!

Looks due to: 

> ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.015931260617070172, tolerance: 0.004999999999999998

maybe we need to increase # of iterations to make this work? If I get some time in the next couple of weeks I can investigate further

**Comment by pizzooid** [comment]
No worries. ;-)

I don't think that increasing the iterations number is going to get rid of all warnings. I think that the elastic net converges too slowly for some problems. The tests just uncover this problem. :-(

Maybe by looking at the inputs it is possible to see for which input values these errors are occuring.

What do you think?

**Review by maxiimilian — APPROVED** [review]
I would appreciate if this patch could get applied because I just ran into the same problem that `FFXRegressor` is not complying with sklearn best practices. Especially `return self` for the `fit()` method is important to allow using the regressor in pipelines.

Let me know if I can be of any help.

**Comment by natekupp** [comment]
@maxiimilian @pizzooid sure, could one of you rebase on master just to confirm this will merge cleanly? and ideally we can get the tests to pass for this PR before landing it

**Comment by natekupp** [comment]
closing this in favor of #50

**Pull request closed without merging**
